import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import getPicturesUrl from "@/utils/getPicturesUrl";
import SearchForm from "@/components/searchForm/searchForm";
import getEndpoint from "@/utils/getEndpoint";

export default function Home() {
  const [currentPictureUrl, setCurrentPictureUrl] = useState<string[] | null>(
    null
  );

  const [inputDate, setInputDate] = useState<string | null>(null);

  const fetchData = async () => {
    const endpoint = getEndpoint(inputDate);
    const picturesURL = await getPicturesUrl(endpoint);
    setCurrentPictureUrl(picturesURL);
  };

  useEffect(() => {
    fetchData();
  }, [inputDate]);

  return (
    <>
      <Head>
        <title>Nasa App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.flex_column}`}>
        <h1>Astronomy Picture of the Day</h1>
        <p>
          Select a date (YYYY-MM-DD) or date range (YYYY-MM-DD - YYYY-MM-DD):
        </p>

        <SearchForm setInputDate={setInputDate} />

        <div className={`${styles.picture_container} ${styles.flex_column}`}>
        {currentPictureUrl &&
          currentPictureUrl.length &&
          currentPictureUrl.map((url, index) => (
            <>
            <p>{index + 1}</p>
                   <img
              key={index}
              className={styles.picture}
              src={url}
              alt="Picture of the Day"
            />
            </>
     
          ))}
        </div>

      </main>
    </>
  );
}
