import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import getPicturesUrl from "@/utils/getPicturesUrl";
import SearchForm from "@/components/searchForm";
import setEndpoint from "@/utils/setEndpoint";

export default function Home() {
  const [currentPictureUrl, setCurrentPictureUrl] = useState<string[] | null>(
    null
  );

  const [inputDate, setInputDate] = useState<string | null>(null);

  const fetchData = async () => {
    const endpoint = setEndpoint(inputDate);
    const picturesURL = await getPicturesUrl(endpoint);
    setCurrentPictureUrl(picturesURL);
  };

  useEffect(() => {
    fetchData();
  }, [inputDate]);

  return (
    <>
      <Head>
        <title>Nasa App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Astronomy Picture of the Day</h1>
        <p>
          Select a date (YYYY-MM-DD) or date range (YYYY-MM-DD - YYYY-MM-DD):
        </p>

        <SearchForm setInputDate={setInputDate} />

        {currentPictureUrl &&
          currentPictureUrl.length &&
          currentPictureUrl.map((url, index) => (
            <img
              key={index}
              className={styles.picture}
              src={url}
              alt="Picture of the Day"
            />
          ))}
      </main>
    </>
  );
}
